### ISSUE TITLE
AWQ RuntimeError

### ISSUE THREAD

**Issue by tom-doerr** [1rgs/jsonformer#44]
Is there a way to make it work with AWQ models?

Output:
```
Fetching 14 files: 100%|███████████████████████████| 14/14 [00:00<00:00, 115591.06it/s]
Replacing layers...: 100%|█████████████████████████████| 32/32 [00:02<00:00, 14.02it/s]
Fusing layers...: 100%|████████████████████████████████| 32/32 [00:04<00:00,  7.79it/s]
2023-12-10 18:50:15.290217: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-10 18:50:15.345000: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-10 18:50:15.951851: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/home/conic/llm_experimentation/./jsonformer_test.py", line 40, in <module>
    generated_data = jsonformer()
  File "/home/conic/.local/lib/python3.10/site-packages/jsonformer/main.py", line 242, in __call__
    generated_data = self.generate_object(
  File "/home/conic/.local/lib/python3.10/site-packages/jsonformer/main.py", line 147, in generate_object
    obj[key] = self.generate_value(schema, obj, key)
  File "/home/conic/.local/lib/python3.10/site-packages/jsonformer/main.py", line 168, in generate_value
    return self.generate_boolean()
  File "/home/conic/.local/lib/python3.10/site-packages/jsonformer/main.py", line 90, in generate_boolean
    output = self.model.forward(input_tensor.to(self.model.device))
  File "/home/conic/.local/lib/python3.10/site-packages/awq/models/base.py", line 37, in forward
    return self.model(*args, **kwargs)
  File "/home/conic/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/conic/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/conic/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1052, in forward
    logits = self.lm_head(hidden_states)
  File "/home/conic/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/conic/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/conic/.local/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Inference tensors cannot be saved for backward. To work around you can make a clone to get a normal tensor and use it in autograd.
```

Code:
```
from jsonformer import Jsonformer
import torch
from awq import AutoAWQForCausalLM
from transformers import AutoTokenizer

model_name_or_path = "TheBloke/Xwin-LM-7B-V0.2-AWQ"
device_map = 'auto'
json_schema = {
    "type": "object",
    "properties": {
        "name": {"type": "string"},
        "age": {"type": "number"},
        "is_student": {"type": "boolean"},
        "courses": {
            "type": "array",
            "items": {"type": "string"}
        }
    }
}

device = 'cuda' if torch.cuda.is_available() else 'cpu'
available_devices = torch.cuda.device_count()
device_name = torch.cuda.get_device_name(device=device)

model = AutoAWQForCausalLM.from_quantized(model_name_or_path, 
                                        fuse_layers=True,
                                          trust_remote_code=False,
                                          safetensors=True,
                                          device_map=device_map,
                                          )

model.device = device
tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, trust_remote_code=False,
        )

prompt = "Generate a person's information based on the following schema:"
jsonformer = Jsonformer(model, tokenizer, json_schema, prompt)
generated_data = jsonformer()

print(generated_data)
```

**Comment by santoryudeadman** [comment]
did you happen to find any workaround on this?

**Comment by tom-doerr** [comment]
@santoryudeadman I switched to lm-format-enforcer: https://github.com/noamgat/lm-format-enforcer
