### ISSUE TITLE
Failed in: RuntimeError: The expanded size of the tensor (151936) must match the existing size (151646) at non-singleton dimension 1.  Target sizes: [1, 151936].  Tensor sizes: [151646]

### ISSUE THREAD

**Issue by daniel7an** [1rgs/jsonformer#56]
```
from jsonformer import Jsonformer
from transformers import AutoModelForCausalLM, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2-0.5B-Instruct")
text_generation_model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen2-0.5B-Instruct")

json_schema = {
  "type": "object",
  "properties": {
    "status": {
      "type": "string",
      "enum": ["success", "failure"]
    },
    "mcq_items": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "question": {
            "type": "string"
          },
          "options": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "option": {
                  "type": "string"
                },
                "reasoning": {
                  "type": "string"
                },
                "label": {
                  "type": "number"
                }
              },
              "required": ["option", "reasoning", "label"]
            }
          },
          "answer": {
            "type": "number"
          }
        },
        "required": ["question", "options", "answer"]
      }
    }
  },
  "required": ["status", "mcq_items"]
}


context = "A story revolving around a man forced by circumstances to participate in a mysterious game of survival. Zheng Kai Si has nothing in his name and in order to pay off his debts, he goes aboard a cruise ship as one of the players in a deadly game. It's a game of lies and deception to outsmart the enemy and emerge victoriously. For the sake of his mother and Liu Qing, Kai Si struggles to survive."
prompt = f"Generate multiple choice question(s) using provided context/topic \
                        and your general knowledge, including 1 correct option and 3 \
                        wrong options. Here is the context: {context}"
jsonformer = Jsonformer(text_generation_model, tokenizer, json_schema, prompt)
generated_data = jsonformer()
print(generated_data)
```

**Fails, when i use "number" as a datatype.**

Error: 

> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
> Traceback (most recent call last):
>   File "C:\Users\Lenovo\Desktop\project_minerva\jsonformer_test.py", line 57, in <module>
>     generated_data = jsonformer()
>                      ^^^^^^^^^^^^
>   File "C:\Users\Lenovo\Desktop\project_minerva\.venv\Lib\site-packages\jsonformer\main.py", line 242, in __call__       
>     generated_data = self.generate_object(
>                      ^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Lenovo\Desktop\project_minerva\.venv\Lib\site-packages\jsonformer\main.py", line 147, in generate_object
>     obj[key] = self.generate_value(schema, obj, key)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Lenovo\Desktop\project_minerva\.venv\Lib\site-packages\jsonformer\main.py", line 178, in generate_value 
>     return self.generate_array(schema["items"], new_array)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Lenovo\Desktop\project_minerva\.venv\Lib\site-packages\jsonformer\main.py", line 192, in generate_array 
>     element = self.generate_value(item_schema, obj)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Lenovo\Desktop\project_minerva\.venv\Lib\site-packages\jsonformer\main.py", line 185, in generate_value 
>     return self.generate_object(schema["properties"], new_obj)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Lenovo\Desktop\project_minerva\.venv\Lib\site-packages\jsonformer\main.py", line 147, in generate_object
>     obj[key] = self.generate_value(schema, obj, key)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Lenovo\Desktop\project_minerva\.venv\Lib\site-packages\jsonformer\main.py", line 178, in generate_value 
>     return self.generate_array(schema["items"], new_array)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Lenovo\Desktop\project_minerva\.venv\Lib\site-packages\jsonformer\main.py", line 192, in generate_array 
>     element = self.generate_value(item_schema, obj)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Lenovo\Desktop\project_minerva\.venv\Lib\site-packages\jsonformer\main.py", line 185, in generate_value 
>     return self.generate_object(schema["properties"], new_obj)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Lenovo\Desktop\project_minerva\.venv\Lib\site-packages\jsonformer\main.py", line 147, in generate_object
>     obj[key] = self.generate_value(schema, obj, key)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Lenovo\Desktop\project_minerva\.venv\Lib\site-packages\jsonformer\main.py", line 162, in generate_value
>     return self.generate_number()
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Lenovo\Desktop\project_minerva\.venv\Lib\site-packages\jsonformer\main.py", line 61, in generate_number 
>     response = self.model.generate(
>                ^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Lenovo\Desktop\project_minerva\.venv\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Lenovo\Desktop\project_minerva\.venv\Lib\site-packages\transformers\generation\utils.py", line 1758, in generate
>     result = self._sample(
>              ^^^^^^^^^^^^^
>   File "C:\Users\Lenovo\Desktop\project_minerva\.venv\Lib\site-packages\transformers\generation\utils.py", line 2410, in _sample
>     next_token_scores = logits_processor(input_ids, next_token_logits)
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Lenovo\Desktop\project_minerva\.venv\Lib\site-packages\transformers\generation\logits_process.py", line 98, in __call__
>     scores = processor(input_ids, scores)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Lenovo\Desktop\project_minerva\.venv\Lib\site-packages\jsonformer\logits_processors.py", line 81, in __call__
>     mask = self.allowed_mask.expand_as(scores)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: The expanded size of the tensor (151936) must match the existing size (151646) at non-singleton dimension 1.  Target sizes: [1, 151936].  Tensor sizes: [151646]

**Comment by wrench1997** [comment]
From my understanding, Qwen cannot generate number.

**Comment by babala2233** [comment]
you need padding this mask or cut this scores,then torch.cuda.empty_cache()
look this:
from typing import List, Union, Dict, Any
from jsonformer.logits_processors import (
    NumberStoppingCriteria,
    OutputNumbersTokens,
    StringStoppingCriteria,
)
from termcolor import cprint
from transformers import PreTrainedModel, PreTrainedTokenizer, AutoModelForCausalLM, AutoTokenizer
import json
import torch

GENERATION_MARKER = "|GENERATION|"


class OutputNumbersTokens(LogitsWarper):
    def __init__(self, tokenizer: PreTrainedTokenizer, prompt: str):
        self.tokenizer = tokenizer
        self.tokenized_prompt = tokenizer(prompt, return_tensors="pt")
        vocab_size = len(tokenizer)
        self.allowed_mask = torch.zeros(vocab_size, dtype=torch.bool)

        for _, token_id in tokenizer.get_vocab().items():
            token_str = tokenizer.decode(token_id).strip()
            if token_str == "" or (
                all(c.isdigit() or c == "." for c in token_str)
                and token_str.count(".") <= 1
            ):
                self.allowed_mask[token_id] = True

    def __call__(self, input_ids, scores):
        # 处理形状不匹配
        if scores.size(1) != len(self.allowed_mask):
            if scores.size(1) > len(self.allowed_mask):
                scores = scores[:, :len(self.allowed_mask)]
            else:
                padding_length = len(self.allowed_mask) - scores.size(1)
                padding = torch.zeros((scores.size(0), padding_length), dtype=scores.dtype, device=scores.device)
                scores = torch.cat([scores, padding], dim=1)

        mask = self.allowed_mask.expand_as(scores)
        scores[~mask] = -float("inf")

        # 显存优化
        del mask
        torch.cuda.empty_cache()  # 及时释放显存

        return scores


class Jsonformer:
    value: Dict[str, Any] = {}

    def __init__(
        self,
        model: PreTrainedModel,
        tokenizer: PreTrainedTokenizer,
        json_schema: Dict[str, Any],
        prompt: str,
        *,
        debug: bool = False,
        max_array_length: int = 10,
        max_number_tokens: int = 6,
        temperature: float = 1.0,
        max_string_token_length: int = 10,
    ):
        self.model = model
        self.tokenizer = tokenizer
        self.json_schema = json_schema
        self.prompt = prompt

        self.number_logit_processor = OutputNumbersTokens(self.tokenizer, self.prompt)

        self.generation_marker = "|GENERATION|"
        self.debug_on = debug
        self.max_array_length = max_array_length

        self.max_number_tokens = max_number_tokens
        self.temperature = temperature
        self.max_string_token_length = max_string_token_length

    def debug(self, caller: str, value: str, is_prompt: bool = False):
        if self.debug_on:
            if is_prompt:
                cprint(caller, "green", end=" ")
                cprint(value, "yellow")
            else:
                cprint(caller, "green", end=" ")
                cprint(value, "blue")

    def generate_number(self, temperature: Union[float, None] = None, iterations=0):
        prompt = self.get_prompt()
        self.debug("[generate_number]", prompt, is_prompt=True)
        input_tokens = self.tokenizer.encode(prompt, return_tensors="pt").to(
            self.model.device
        )

        # 手动创建注意力掩码
        attention_mask = torch.ones_like(input_tokens)

        response = self.model.generate(
            input_tokens,
            max_new_tokens=self.max_number_tokens,
            num_return_sequences=1,
            logits_processor=[self.number_logit_processor],
            stopping_criteria=[
                NumberStoppingCriteria(self.tokenizer, len(input_tokens[0]))
            ],
            temperature=temperature or self.temperature,
            pad_token_id=self.tokenizer.eos_token_id,
            attention_mask=attention_mask
        )
        response = self.tokenizer.decode(response[0], skip_special_tokens=True)

        response = response[len(prompt):]
        response = response.strip().rstrip(".")
        self.debug("[generate_number]", response)
        try:
            return float(response)
        except ValueError:
            if iterations > 3:
                raise ValueError("Failed to generate a valid number")

            return self.generate_number(temperature=self.temperature * 1.3, iterations=iterations + 1)

    def generate_boolean(self) -> bool:
        prompt = self.get_prompt()
        self.debug("[generate_boolean]", prompt, is_prompt=True)

        input_tensor = self.tokenizer.encode(prompt, return_tensors="pt")
        output = self.model.forward(input_tensor.to(self.model.device))
        logits = output.logits[0, -1]

        # todo: this assumes that "true" and "false" are both tokenized to a single token
        # this is probably not true for all tokenizers
        # this can be fixed by looking at only the first token of both "true" and "false"
        true_token_id = self.tokenizer.convert_tokens_to_ids("true")
        false_token_id = self.tokenizer.convert_tokens_to_ids("false")

        result = logits[true_token_id] > logits[false_token_id]

        self.debug("[generate_boolean]", result)

        return result.item()

    def generate_string(self) -> str:
        prompt = self.get_prompt() + '"'
        self.debug("[generate_string]", prompt, is_prompt=True)
        input_tokens = self.tokenizer.encode(prompt, return_tensors="pt").to(
            self.model.device
        )

        # 手动创建注意力掩码
        attention_mask = torch.ones_like(input_tokens)

        response = self.model.generate(
            input_tokens,
            max_new_tokens=self.max_string_token_length,
            num_return_sequences=1,
            temperature=self.temperature,
            stopping_criteria=[
                StringStoppingCriteria(self.tokenizer, len(input_tokens[0]))
            ],
            pad_token_id=self.tokenizer.eos_token_id,
            attention_mask=attention_mask
        )

        # Some models output the prompt as part of the response
        # This removes the prompt from the response if it is present
        if (
            len(response[0]) >= len(input_tokens[0])
            and (response[0][:len(input_tokens[0])] == input_tokens).all()
        ):
            response = response[0][len(input_tokens[0]):]
        if response.shape[0] == 1:
            response = response[0]

        response = self.tokenizer.decode(response, skip_special_tokens=True)

        self.debug("[generate_string]", "|" + response + "|")

        if response.count('"') < 1:
            return response

        return response.split('"')[0].strip()

    def generate_object(
        self, properties: Dict[str, Any], obj: Dict[str, Any]
    ) -> Dict[str, Any]:
        for key, schema in properties.items():
            self.debug("[generate_object] generating value for", key)
            obj[key] = self.generate_value(schema, obj, key)
        return obj

    def generate_value(
        self,
        schema: Dict[str, Any],
        obj: Union[Dict[str, Any], List[Any]],
        key: Union[str, None] = None,
    ) -> Any:
        schema_type = schema["type"]
        if schema_type == "number":
            if key:
                obj[key] = self.generation_marker
            else:
                obj.append(self.generation_marker)
            return self.generate_number()
        elif schema_type == "boolean":
            if key:
                obj[key] = self.generation_marker
            else:
                obj.append(self.generation_marker)
            return self.generate_boolean()
        elif schema_type == "string":
            if key:
                obj[key] = self.generation_marker
            else:
                obj.append(self.generation_marker)
            return self.generate_string()
        elif schema_type == "array":
            new_array = []
            obj[key] = new_array
            return self.generate_array(schema["items"], new_array)
        elif schema_type == "object":
            new_obj = {}
            if key:
                obj[key] = new_obj
            else:
                obj.append(new_obj)
            return self.generate_object(schema["properties"], new_obj)
        else:
            raise ValueError(f"Unsupported schema type: {schema_type}")

    def generate_array(self, item_schema: Dict[str, Any], obj: Dict[str, Any]) -> list:
        for _ in range(self.max_array_length):
            # forces array to have at least one element
            element = self.generate_value(item_schema, obj)
            obj[-1] = element

            obj.append(self.generation_marker)
            input_prompt = self.get_prompt()
            obj.pop()
            input_tensor = self.tokenizer.encode(input_prompt, return_tensors="pt")
            output = self.model.forward(input_tensor.to(self.model.device))
            logits = output.logits[0, -1]

            top_indices = logits.topk(30).indices
            sorted_token_ids = top_indices[logits[top_indices].argsort(descending=True)]

            found_comma = False
            found_close_bracket = False

            for token_id in sorted_token_ids:
                decoded_token = self.tokenizer.decode(token_id)
                if ',' in decoded_token:
                    found_comma = True
                    break
                if ']' in decoded_token:
                    found_close_bracket = True
                    break

            if found_close_bracket or not found_comma:
                break

            # 每次循环后释放显存
            del input_tensor, output, logits
            torch.cuda.empty_cache()

        return obj

    def get_prompt(self):
        template = """{prompt}\nOutput result in the following JSON schema format:\n{schema}\nResult: {progress}"""
        progress = json.dumps(self.value)
        gen_marker_index = progress.find(f'"{self.generation_marker}"')
        if gen_marker_index != -1:
            progress = progress[:gen_marker_index]
        else:
            raise ValueError("Failed to find generation marker")

        prompt = template.format(
            prompt=self.prompt,
            schema=json.dumps(self.json_schema),
            progress=progress,
        )

        return prompt

    def __call__(self) -> Dict[str, Any]:
        self.value = {}
        generated_data = self.generate_object(
            self.json_schema["properties"], self.value
        )
        return generated_data
